---
#
# Connect via console with console argument
#
- name: 'Console argument'
  hosts: r0
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos

  tasks:
    - name: "Get facts"
      juniper_junos_facts:
        console: "--telnet=r0.ts,15007"

    - name: "Print Junos Version"
      debug:
        var: junos.version
