---
#
# User port argument
#
- name: 'NETCONF over port 22'
  hosts: r0
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos

  tasks:
    - name: "Get facts"
      juniper_junos_facts:
        port: 22

    - name: "Print Junos Version"
      debug:
        var: junos.version
