---
#
# Collect Pre Snapshot of storage
#
- name: 'Collect Pre Snapshot of storage'
  hosts: r0
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos

  tasks:
    - name: 'Collect Pre Snapshot of storage'
      juniper_junos_jsnapy:
        action: "snap_pre"
        test_files: "./test_junos_storage.yml"
      register: response

    - name: "Print the response"
      debug:
        var: response
