---
#
# Aliases for the arguments used by the core modules.
#
- name: 'Aliases for core argument names'
  hosts: r0
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos

  tasks:
    - name: "Get facts"
      juniper_junos_facts:
        username: "user"
        password: "user123"

    - name: "Print Junos Version"
      debug:
        var: junos.version
