---
#
# Reboot. Both REs if it's a dual RE system.
#
- name: "Reboot. Both REs if it's a dual RE system."
  hosts: r6
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos

  tasks:
    - name: "Reboot. Both REs if it's a dual RE system."
      juniper_junos_system:
        action: 'reboot'
      register: response

    - name: "Print the response"
      debug:
        var: response
