---
#
# Rollback
#
- name: 'Rollback to previous config'
  hosts: r0
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos

  tasks:
    - name: "Rollback to previous config"
      juniper_junos_config:
        rollback: 1
      register: response

    - name: "Print the differences"
      debug:
        var: response.diff_lines
