---
#
# The response now contains the command output
#
- name: 'Command output in response'
  hosts: r0
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos

  tasks:
    - name: "show lldp neighbors"
      juniper_junos_command:
        command: "show lldp neighbors"
      register: response

    - name: "Print the response"
      debug:
        var: response
